project_name: comeet
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    ldflags: -s -w
    env:
        - CGO_ENABLED=0
    goos: 
      - darwin
      - linux
    goarch: 
      - 386
      - amd64
      - arm
    goarm:
      - 6
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'typo'
      - 'Merge pull request'
      - 'Merge branch'

brews:
  - 
    tap:
      owner: GGP1
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/GGP1/comeet
    description: Service that keeps track of events from multiple calendar services and accounts, and sends you notifications through different platforms that can be completely customized.
    license: Apache 2.0

scoop:
  bucket:
    owner: GGP1
    name: scoop-bucket
  homepage:  https://github.com/GGP1/comeet
  description: Service that keeps track of events from multiple calendar services and accounts, and sends you notifications through different platforms that can be completely customized.
  license: Apache 2.0

nfpms:
- 
  formats:
    - deb
  maintainer: GGP1
  homepage: https://github.com/GGP1/comeet
  description: Service that keeps track of events from multiple calendar services and accounts, and sends you notifications through different platforms that can be completely customized.
  license: Apache 2.0
  file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows